import uuid
from db import db, now
from models import SettingsInput

DISTRICTS = ['Aveiro','Beja','Braga','Bragança','Castelo Branco','Coimbra','Évora','Faro','Guarda','Leiria','Lisboa','Portalegre','Porto','Santarém','Setúbal','Viana do Castelo','Vila Real','Viseu','Açores','Madeira']
DEVICES = [
 ('iphone','iPhone','iPhone','O seu iPhone, de volta ao dia a dia.','Your iPhone, back to everyday life.','Ecrã partido, bateria que já não acompanha o ritmo ou dificuldade em carregar? Descreva o que aconteceu ao seu iPhone e peça uma avaliação adequada ao modelo.','Cracked screen, a battery that cannot keep up or charging difficulties? Tell us what happened and request an assessment for your iPhone model.'),
 ('smartphone','Smartphone','Smartphone','Mais vida para o seu smartphone.','More life for your smartphone.','Um problema no telemóvel não tem de significar um equipamento novo. Indique a marca, o modelo e os sintomas para analisarmos as opções de reparação.','A phone problem does not have to mean a new device. Share the brand, model and symptoms so we can assess the repair options.'),
 ('macbook','MacBook','MacBook','Volte às suas melhores ideias.','Get back to your best ideas.','Do arranque ao teclado, pequenos sintomas podem ter causas muito diferentes. Identifique o seu MacBook Air ou Pro e conte-nos o que deixou de funcionar.','From startup to keyboard issues, similar symptoms can have different causes. Identify your MacBook Air or Pro and tell us what stopped working.'),
 ('portatil','Portátil','Laptop','O seu trabalho não precisa de parar.','Your work does not need to stop.','Sobreaquecimento, lentidão, ecrã danificado ou bateria sem autonomia? Um diagnóstico do portátil ajuda a perceber se a reparação faz sentido para si.','Overheating, slow performance, a damaged display or poor battery life? A laptop assessment helps you decide whether a repair makes sense.'),
 ('tablet','Tablet','Tablet','Um novo capítulo para o seu tablet.','A new chapter for your tablet.','Para estudar, trabalhar ou ver a sua série preferida. Peça uma avaliação do ecrã, bateria, carregamento ou software do seu tablet, indicando o modelo exato.','For studying, working or watching your favourite series. Request an assessment of your tablet screen, battery, charging or software, including its exact model.'),
 ('computador','Computador','Computer','De volta ao desempenho que precisa.','Back to the performance you need.','Um computador que não liga ou perde desempenho precisa de uma análise cuidada. Descreva os componentes, o sistema operativo e os sinais apresentados.','A computer that will not start or loses performance needs careful assessment. Describe its components, operating system and symptoms.'),
 ('outros','Outros dispositivos','Other devices','Conte-nos o que precisa de reparar.','Tell us what needs repairing.','Não encontra o seu equipamento? Envie a categoria, a marca e uma descrição do problema. A possibilidade de intervenção é confirmada antes de qualquer compromisso.','Cannot find your device? Send its category, brand and a description of the issue. Repair availability is confirmed before any commitment.')]

FAQ = [
 {'q':'Quanto custa a reparação?','a':'O valor depende do modelo, do problema e das peças necessárias. O orçamento é apresentado depois de avaliarmos o pedido; não é possível indicar um preço rigoroso apenas pelo sintoma.','q_en':'How much does a repair cost?','a_en':'The cost depends on the model, fault and parts needed. A quote follows assessment; a symptom alone is not enough to give an accurate price.'},
 {'q':'A reparação começa sem a minha autorização?','a':'O pedido de orçamento não autoriza uma reparação. Confirme as condições, o valor e a disponibilidade com a equipa antes de avançar.','q_en':'Does my enquiry authorise a repair?','a_en':'No. A quote request does not authorise repairs. Confirm the conditions, price and availability with the team before proceeding.'},
 {'q':'Devo fazer uma cópia de segurança?','a':'Sempre que possível, faça uma cópia de segurança antes de entregar o equipamento. Não partilhe palavras-passe, códigos de desbloqueio ou dados bancários no formulário.','q_en':'Should I back up my data?','a_en':'Whenever possible, back up your device before handing it over. Do not share passwords, unlock codes or banking details in the enquiry form.'},
 {'q':'Como confirmo o atendimento na minha zona?','a':'Indique a cidade ou o código postal no pedido. A equipa confirma a cobertura e a forma de atendimento; a presença de uma cidade no formulário não significa que exista uma loja nessa localização.','q_en':'How do I check availability in my area?','a_en':'Include your city or postcode. The team will confirm coverage and service arrangements. A city in the form does not imply a physical store there.'}]

async def add_page(doc):
    await db.pages.update_one({'slug':doc['slug']}, {'$setOnInsert':{'id':str(uuid.uuid4()),'created_at':now(),'updated_at':now(),'status':'draft','noindex':True,'verified':False,'faqs':[],**doc}}, upsert=True)

async def seed():
    await db.pages.create_index('slug', unique=True)
    await db.pages.create_index('id', unique=True)
    await db.leads.create_index('created_at')
    await db.leads.create_index('id', unique=True)
    await db.admins.create_index('id', unique=True)
    await db.sessions.create_index('expires', expireAfterSeconds=0)
    await db.rate_limits.create_index('expires', expireAfterSeconds=0)
    await db.settings.update_one({'id':'business'}, {'$setOnInsert':{'id':'business',**SettingsInput().model_dump()}}, upsert=True)
    if await db.meta.find_one({'id':'seed-v1'}):
        return
    for slug, name, en, tagline, tagline_en, intro, intro_en in DEVICES:
        await add_page({'slug':f'reparacao-{slug}','kind':'service','title':f'Reparação de {name}','title_en':f'{en} repair','status':'published','device':name,'service':name,'intro':intro,'intro_en':intro_en,'category':tagline,'content':f'Antes de reparar o seu {name}\n\nAnote quando o problema começou e se houve uma queda, contacto com líquidos ou uma atualização recente. Estes detalhes ajudam a distinguir um problema físico de uma falha de software. Se o equipamento ainda liga, guarde os ficheiros importantes numa cópia de segurança.\n\nUma avaliação ajustada ao equipamento\n\nA referência exata do modelo permite confirmar a compatibilidade das peças e a possibilidade de intervenção. Informe também se o equipamento já foi reparado. O preço, o prazo, a disponibilidade e as condições aplicáveis são confirmados individualmente antes da reparação.\n\nUma decisão informada\n\nCompare o custo da intervenção com o estado geral e a utilização que pretende dar ao dispositivo. Se não souber a origem da avaria, descreva apenas os sintomas. Não é necessário escolher uma peça ou um diagnóstico antes de falar connosco.','content_en':f'Before repairing your {en}\n\nNote when the problem started and whether there was a drop, liquid contact or a recent update. This helps distinguish hardware faults from software issues. If the device still starts, back up important files.\n\nAn assessment for your device\n\nThe exact model helps confirm parts compatibility and repair availability. Mention any previous repairs. Price, timing, availability and applicable conditions are confirmed individually before work begins.\n\nAn informed decision\n\nCompare the repair cost with the overall condition of the device and your intended use. If you do not know the cause, simply describe the symptoms. You do not need to diagnose it before contacting us.','faqs':FAQ,'image':'/images/repair-hero.webp'})
    repairs=[('ecra','Ecrã','Screen','O vidro está partido, o toque falha ou surgiram linhas na imagem? Evite pressionar o ecrã e indique se o telefone ainda responde.'),('bateria','Bateria','Battery','A autonomia diminuiu ou o iPhone desliga-se inesperadamente? Indique a saúde da bateria, quando disponível. Se existir inchaço, pare de utilizar e carregar o equipamento.'),('camera','Câmara','Camera','Fotografias desfocadas, imagem preta ou vibração ao focar podem ter causas diferentes. Diga-nos se o problema afeta a câmara frontal, traseira ou ambas.'),('conector-carga','Conector de carga','Charging port','Antes de atribuir a falha ao conector, experimente um cabo e carregador compatíveis em bom estado. Não introduza objetos metálicos na porta.'),('danos-agua','Danos por líquidos','Liquid damage','Desligue o equipamento, não o carregue e evite arroz ou fontes de calor. Informe qual o líquido e há quanto tempo ocorreu o contacto.')]
    for slug,name,en,intro in repairs:
        await add_page({'slug':f'reparacao-iphone/{slug}','kind':'repair','title':f'iPhone: {name.lower()}','title_en':f'iPhone {en.lower()} repair','status':'published','service':name,'device':'iPhone','intro':intro,'intro_en':f'Request an assessment for your iPhone {en.lower()}. Tell us the model, symptoms and when the issue started.','content':intro+'\n\nIndique o modelo exato do seu iPhone e se já foi sujeito a intervenções. A possibilidade de reparação, peças, orçamento e prazo dependem de uma avaliação. Faça uma cópia de segurança se for seguro utilizar o equipamento. Nunca partilhe palavras-passe neste pedido.','content_en':'Include your exact iPhone model and any previous repair history. Repair availability, parts, price and timing depend on assessment. Back up your data if it is safe to use the device. Never share passwords in the enquiry.','faqs':FAQ[:3]})
    import unicodedata
    def slugify(text):
        return unicodedata.normalize('NFKD',text).encode('ascii','ignore').decode().lower().replace(' ','-')
    for name in DISTRICTS:
        await add_page({'slug':f'distritos/{slugify(name)}','kind':'district','title':name,'district':name})
    cities=[('Lisboa','Lisboa',['1000','1100','1200','1300','1400','1500','1600','1700','1800','1900']),('Sintra','Lisboa',['2710','2725','2735']),('Cascais','Lisboa',['2750','2765']),('Amadora','Lisboa',['2700','2610']),('Oeiras','Lisboa',['2780','2790']),('Loures','Lisboa',['2670']),('Almada','Setúbal',['2800','2810']),('Setúbal','Setúbal',['2900','2910']),('Porto','Porto',['4000','4050','4100','4150','4200','4250','4300','4350']),('Vila Nova de Gaia','Porto',['4400','4430']),('Matosinhos','Porto',['4450','4460']),('Maia','Porto',['4470']),('Braga','Braga',['4700','4710']),('Coimbra','Coimbra',['3000','3030']),('Aveiro','Aveiro',['3800','3810']),('Faro','Faro',['8000','8005'])]
    for city,district,prefixes in cities:
        await db.geography.update_one({'city':city},{'$setOnInsert':{'city':city,'district':district,'slug':slugify(city),'postal_prefixes':prefixes}},upsert=True)
        await add_page({'slug':slugify(city),'kind':'municipality','title':city,'district':district,'municipality':city,'postal_prefixes':prefixes})
    for name in ['Apple','Samsung','Xiaomi','Huawei','Google Pixel','OnePlus','OPPO','Motorola','Dell','HP','Lenovo','ASUS','Acer','Microsoft Surface']:
        await add_page({'slug':f'marcas/{slugify(name)}','kind':'brand','title':name,'brand':name})
    articles=[
      ('quando-substituir-bateria-iphone','Quando deve substituir a bateria do iPhone?','When should you replace your iPhone battery?','iPhone','A bateria já não chega ao fim do dia? Saiba quais os sinais que justificam uma avaliação.','Is your battery struggling to last the day? Learn which signs call for an assessment.', 'O que significa a saúde da bateria?\n\nNas definições do iPhone pode consultar a capacidade máxima da bateria. Esta estimativa diminui com o uso e não é, por si só, um diagnóstico. Observe também a autonomia real, os desligamentos inesperados e eventuais avisos do sistema.\n\nAntes de pensar numa substituição\n\nConsulte o consumo por aplicação, reduza a atividade em segundo plano de apps que não utiliza e confirme se o sistema está atualizado. Uma atualização recente pode provocar consumo temporário enquanto o sistema reorganiza dados.\n\nSinais que exigem atenção\n\nSe o ecrã se levantar, a carcaça deformar ou surgir calor anormal, deixe de utilizar e carregar o equipamento. Não pressione nem perfure a bateria. Procure uma avaliação técnica antes de voltar a ligá-lo.\n\nComo decidir\n\nA idade do dispositivo, o seu estado geral e a utilização diária ajudam a avaliar uma substituição. Peça um orçamento para o modelo exato e confirme as condições aplicáveis. Guarde os seus dados antes de entregar o equipamento.', 'What does battery health mean?\n\nYour iPhone settings show an estimate of maximum battery capacity. It decreases with use and is not a diagnosis on its own. Also consider real-world battery life, unexpected shutdowns and system warnings.\n\nBefore replacing the battery\n\nCheck battery use by app, reduce unnecessary background activity and update your system. A recent update can temporarily increase consumption while data is reorganised.\n\nWarning signs\n\nIf the screen lifts, the casing deforms or unusual heat develops, stop using and charging the phone. Do not press or puncture the battery. Seek assessment before switching it on again.\n\nMaking a decision\n\nConsider device age, overall condition and daily usage. Request a quote for your exact model and confirm the conditions. Back up data before handing over the device.'),
      ('telemovel-caiu-na-agua','O telemóvel caiu na água. E agora?','Dropped your phone in water. What now?','Conselhos','Os primeiros gestos fazem a diferença. Saiba o que evitar depois do contacto com líquidos.','Your first actions matter. Learn what to avoid after liquid contact.','Desligue e não carregue\n\nRetire o equipamento do líquido, desligue-o se for possível fazê-lo em segurança e remova os acessórios externos. Não ligue o carregador para testar: a presença de humidade pode agravar os danos.\n\nEsqueça o arroz e o secador\n\nO arroz não remove resíduos nem corrosão interna. O calor direto pode danificar componentes e adesivos. Seque apenas a superfície com um pano macio e mantenha o equipamento num local seco e ventilado.\n\nRegiste o que aconteceu\n\nInforme qual o líquido, o tempo de contacto e se o telefone estava ligado. Água salgada, bebidas e água limpa podem deixar resíduos diferentes. Mesmo que volte a funcionar, podem surgir falhas mais tarde.\n\nPeça uma avaliação\n\nA recuperação do equipamento e dos dados não pode ser garantida sem análise. Não tente abrir o telefone sem ferramentas e experiência. Indique o modelo no pedido e aguarde orientações específicas.','Switch off and do not charge\n\nRemove the device from liquid, switch it off if safe and remove external accessories. Do not connect a charger to test it: moisture can make damage worse.\n\nSkip rice and hairdryers\n\nRice does not remove residue or internal corrosion. Direct heat can damage components and adhesives. Dry the exterior with a soft cloth and leave the device in a dry, ventilated place.\n\nRecord what happened\n\nShare the type of liquid, exposure duration and whether the phone was on. Salt water, drinks and clean water leave different residues. Faults can appear later even if the phone starts working again.\n\nRequest an assessment\n\nDevice and data recovery cannot be guaranteed without examination. Do not open the phone without suitable tools and experience. Include its model and wait for specific advice.'),
      ('macbook-nao-liga','O MacBook não liga: por onde começar?','MacBook will not turn on: where to start?','MacBook','Algumas verificações simples antes de pedir assistência para o seu MacBook.','A few simple checks before requesting help with your MacBook.','Confirme a alimentação\n\nVerifique a tomada, o carregador e o cabo. Use acessórios compatíveis e sem danos visíveis. Deixe o equipamento ligado à corrente durante algum tempo antes de tentar arrancar, exceto se existirem sinais de líquido ou bateria danificada.\n\nEcrã preto ou computador desligado?\n\nObserve se há sons, luzes ou resposta do teclado. Um ecrã sem imagem não significa necessariamente que o MacBook não esteja ligado. Remova periféricos externos e registe os sinais observados.\n\nO modelo importa\n\nOs procedimentos variam entre modelos Intel e Apple silicon. Consulte as instruções oficiais da Apple para a referência exata; não aplique combinações de teclas aleatórias.\n\nQuando parar\n\nSe houver odor anormal, calor excessivo ou contacto com líquidos, desligue a alimentação. Peça uma avaliação, descrevendo o que aconteceu antes da falha. Não é possível concluir que a placa lógica precisa de substituição apenas porque o equipamento não liga.','Check power first\n\nCheck the socket, charger and cable. Use compatible accessories without visible damage. Leave the device connected for a while before trying to start it, unless there are signs of liquid or battery damage.\n\nBlack screen or no power?\n\nListen for sounds and look for lights or keyboard responses. No display does not necessarily mean the MacBook is off. Remove external peripherals and record what you observe.\n\nThe model matters\n\nProcedures differ between Intel and Apple silicon models. Follow official Apple instructions for your exact device rather than random key combinations.\n\nWhen to stop\n\nIf there is an unusual smell, excessive heat or liquid contact, disconnect power. Request an assessment and describe events before the failure. Failure to start alone does not prove that the logic board needs replacement.')]
    for slug,title,en,cat,intro,ien,content,cen in articles:
        await add_page({'slug':'blog/'+slug,'kind':'blog','title':title,'title_en':en,'intro':intro,'intro_en':ien,'content':content,'content_en':cen,'category':cat,'status':'published','noindex':False,'verified':True,'image':'/images/repair-small.webp'})
    for channel in ['google','meta']:
        await add_page({'slug':f'campanhas/{channel}-reparacao','kind':'campaign','title':'O seu dispositivo merece uma segunda vida.','title_en':'Your device deserves a second life.','intro':'Conte-nos o problema. Peça uma avaliação e conheça as opções para o seu equipamento.','intro_en':'Tell us the problem. Request an assessment and explore options for your device.','campaign_type':channel,'content':'Um pedido, uma conversa, uma decisão informada. Indique o modelo e os sintomas. A disponibilidade, o orçamento e o prazo são confirmados individualmente.','content_en':'One enquiry, one conversation, an informed decision. Share the model and symptoms. Availability, price and timing are confirmed individually.','faqs':FAQ[:2]})
    await db.meta.update_one({'id':'seed-v1'},{'$set':{'completed_at':now()}},upsert=True)