import { useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Menu, X, ChevronDown, Globe2, Recycle, ShieldCheck, MessageCircle } from 'lucide-react';
import { useSite, useText, localPath } from '../lib/context';
import { ContactActions } from './ContactActions';

export const Logo=({footer=false})=><span className={`logo ${footer?'logo-light':''}`}><span className="logo-symbol">g<span/></span><span>Glenn<span className="logo-tek">Tek</span><i/></span></span>;
export const Header=()=>{
 const [open,setOpen]=useState(false);const {lang,pages}=useSite();const t=useText();const location=useLocation();
 const currentPage=pages.find(p=>'/'+p.slug===location.pathname.replace(/^\/en/,'').replace(/\/$/,''));
 const context=Object.fromEntries(['service','device','brand','model','district','municipality'].map(k=>[k,currentPage?.[k]||'']));
 const links=[['/reparacoes','Reparações','Repairs'],['/marcas','Marcas','Brands'],['/localizacoes','Localizações','Locations'],['/como-funciona','Como funciona','How it works'],['/sobre-nos','Sobre nós','About us'],['/blog','Blog','Blog'],['/contactos','Contactos','Contact']];
 const otherPath=lang==='en'?(location.pathname.replace(/^\/en/,'')||'/'):'/en'+(location.pathname==='/'?'/':location.pathname);
 return <><div className="utility-bar"><div className="container utility-inner"><span data-testid="utility-message"><Recycle size={13}/>{t('Mais vida para a sua tecnologia. Menos desperdício.','More life for your technology. Less waste.')}</span><span className="utility-right" data-testid="utility-region">{t('Tecnologia com uma segunda oportunidade.','Technology with a second chance.')}<span className="portugal-mark"/>Portugal</span></div></div>
 <header className="site-header"><div className="container header-inner"><Link data-testid="header-logo" aria-label="GlennTek início" to={localPath('/',lang)} onClick={()=>setOpen(false)}><Logo/></Link><nav className={open?'main-nav is-open':'main-nav'} aria-label={t('Navegação principal','Main navigation')}>{links.map(([path,pt,en],i)=><NavLink key={path} to={localPath(path,lang)} data-testid={`nav-${path.slice(1)}`} onClick={()=>setOpen(false)}>{t(pt,en)}{i<3&&<ChevronDown size={11}/>}</NavLink>)}</nav><div className="header-actions"><Link className="language-link" data-testid="language-toggle" to={otherPath} aria-label={lang==='pt'?'Switch to English':'Mudar para Português'}><Globe2 size={15}/>{lang==='pt'?'EN':'PT'}</Link><ContactActions id="header" compact context={context}/><button className="mobile-toggle" data-testid="mobile-menu-toggle" aria-label="Menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div></header></>
};
export const Footer=()=>{
 const {lang,settings}=useSite();const t=useText();const link=(p,label,id)=><Link key={id} data-testid={`footer-${id}`} to={localPath(p,lang)}>{label}</Link>;
 return <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Link data-testid="footer-logo" to={localPath('/',lang)}><Logo footer/></Link><p data-testid="footer-description">{t('A tecnologia faz parte da sua vida. Ajudamos a dar-lhe uma segunda oportunidade.','Technology is part of your life. We help give it a second chance.')}</p><span className="footer-country" data-testid="footer-country"><span className="portugal-mark"/>{t('Pensado para Portugal.','Made for Portugal.')}</span></div><div><h3>{t('Reparações','Repairs')}</h3>{['iphone','smartphone','macbook','portatil','tablet','computador'].map((d,i)=>link('/reparacao-'+d,['iPhone','Smartphone','MacBook',t('Portátil','Laptop'),'Tablet',t('Computador','Computer')][i],d))}</div><div><h3>GlennTek</h3>{link('/sobre-nos',t('Sobre nós','About us'),'about')}{link('/como-funciona',t('Como funciona','How it works'),'how')}{link('/localizacoes',t('Localizações','Locations'),'locations')}{link('/blog',t('Conselhos e novidades','Tips and insights'),'blog')}{link('/faq',t('Perguntas frequentes','Frequently asked questions'),'faq')}</div><div><h3>{t('Vamos conversar?','Let’s talk.')}</h3><p>{t('Conte-nos o que aconteceu ao seu equipamento.','Tell us what happened to your device.')}</p>{link('/orcamento',<>{t('Pedir um orçamento','Request a quote')}<ArrowUpRight size={16}/></>,'quote')}{settings.email&&<a data-testid="footer-email" href={`mailto:${settings.email}`}>{settings.email}</a>}{link('/contactos',t('Todos os contactos','All contact options'),'contacts')}<div className="footer-secure"><ShieldCheck size={17}/>{t('Os seus dados, protegidos.','Your data, protected.')}</div></div></div><div className="container footer-bottom"><span data-testid="copyright">© {new Date().getFullYear()} GlennTek. {t('Todos os direitos reservados.','All rights reserved.')}</span><div>{link('/privacidade',t('Privacidade','Privacy'),'privacy')}{link('/cookies','Cookies','cookies')}{link('/termos',t('Termos e condições','Terms and conditions'),'terms')}<button data-testid="cookie-settings-open" onClick={()=>window.dispatchEvent(new Event('open-cookie-settings'))}>{t('Gerir cookies','Cookie settings')}</button></div></div></footer>
};
export const MobileBar=({context={}})=><div className="mobile-conversion-bar"><ContactActions context={context} id="mobile-bar"/></div>;
export const Breadcrumb=({items=[]})=>{const {lang}=useSite();const t=useText();return <nav className="breadcrumb" aria-label="Breadcrumb"><Link data-testid="breadcrumb-home" to={localPath('/',lang)}>{t('Início','Home')}</Link>{items.map((item,i)=><span key={i}><span className="breadcrumb-separator">/</span>{item.path?<Link data-testid={`breadcrumb-${i}`} to={localPath(item.path,lang)}>{item.label}</Link>:<span data-testid={`breadcrumb-current-${i}`}>{item.label}</span>}</span>)}</nav>};
export const SectionHeading=({eyebrow,title,description,link,label,id='section'})=><div className="section-heading"><div>{eyebrow&&<div className="eyebrow" data-testid={`${id}-eyebrow`}>{eyebrow}</div>}<h2 data-testid={`${id}-title`}>{title}</h2>{description&&<p data-testid={`${id}-description`}>{description}</p>}</div>{link&&<Link className="text-link" data-testid={`${id}-link`} to={link}>{label}<ArrowUpRight size={17}/></Link>}</div>;