import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, CheckCircle2, ShieldCheck, Loader2 } from 'lucide-react';
import { Input } from './ui/input';
import { Textarea } from './ui/textarea';
import { useSite,useText,localPath } from '../lib/context';
import { api,errorText,track } from '../lib/api';
import { ContactActions } from './ContactActions';

export const QuoteForm=({context={},short=false})=>{
 const {districts,lang,settings}=useSite();const t=useText();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(null);const [started,setStarted]=useState(false);
 const initialIssue=({'Ecrã':'Ecrã','Bateria':'Bateria','Conector de carga':'Carregamento','Câmara':'Câmara','Danos por líquidos':'Líquidos','Software e desempenho':'Software'}[context.issue||context.service]||'');
 const [form,setForm]=useState({name:'',phone:'',email:'',whatsapp:'',district:context.district||'',municipality:context.municipality||'',postal_code:'',device:context.device||'',brand:context.brand||'',model:context.model||'',issue:initialIssue,description:'',preferred_contact:'whatsapp',consent:false,marketing_consent:false,website:''});
 const change=e=>setForm(f=>({...f,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
 const start=()=>{if(!started){track('quote_started',{service:context.service||'',device:context.device||''});setStarted(true)}};
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{let campaign={};try{campaign=JSON.parse(sessionStorage.getItem('gt-campaign')||'{}')}catch{}const result=await api.post('/leads',{...form,email:form.email||null,language:lang,context:{...Object.fromEntries(Object.entries(context).filter(([k,v])=>typeof v==='string')),...campaign,url:window.location.href,source:campaign.utm_source||'website'}});setSuccess(result.data);track('quote_submitted',{service:context.service||'',lead_id:result.data.id});track('form_submission',{form:'repair_quote'});if(window.gtag&&settings.ads_id&&settings.ads_conversion_label){let consent={};try{consent=JSON.parse(localStorage.getItem('gt-consent')||'{}')}catch{}if(consent.marketing)window.gtag('event','conversion',{send_to:`${settings.ads_id}/${settings.ads_conversion_label}`})}}catch(err){setError(errorText(err))}finally{setBusy(false)}};
 const field=(name,label,options={})=><label className={`form-field ${options.wide?'wide':''}`} key={name}><span>{label}{options.required&&<i> *</i>}</span><Input data-testid={`quote-${name}`} name={name} value={form[name]} onChange={change} placeholder={options.placeholder||''} type={options.type||'text'} required={options.required} maxLength={options.maxLength||150} pattern={options.pattern} autoComplete={options.autoComplete}/></label>;
 const select=(name,label,items,required=false)=><label className="form-field" key={name}><span>{label}{required&&<i> *</i>}</span><select data-testid={`quote-${name}`} name={name} value={form[name]} onChange={change} required={required}><option value="">{t('Selecionar','Select')}</option>{items.map(item=><option key={typeof item==='string'?item:item[0]} value={typeof item==='string'?item:item[0]}>{typeof item==='string'?item:item[1]}</option>)}</select></label>;
 if(success)return <div className="quote-success" id="orcamento" data-testid="quote-success" role="status"><CheckCircle2 size={46}/><h2>{t('Pedido recebido. Obrigado!','Enquiry received. Thank you!')}</h2><p>{t('A equipa irá analisar o seu pedido e entrar em contacto pelo método escolhido.','The team will review your enquiry and contact you using your preferred method.')}</p><span className="reference" data-testid="quote-reference">{t('Referência','Reference')}: {success.reference}</span><ContactActions context={context} id="success" quote={false}/><button className="text-link" data-testid="quote-new-request" onClick={()=>{setSuccess(null);setStarted(false);setForm({...form,description:'',issue:'',consent:false})}}>{t('Enviar outro pedido','Send another enquiry')}<ArrowUpRight size={16}/></button></div>;
 return <form id="orcamento" className="quote-form" data-testid="quote-form" onSubmit={submit} onFocus={start}><div className="form-topline"><span>{t('O seu pedido começa aqui.','Your enquiry starts here.')}</span><span>{t('* Campos obrigatórios','* Required fields')}</span></div><div className="form-grid">
 {field('name',t('Nome','Name'),{required:true,placeholder:t('O seu nome','Your name'),autoComplete:'name'})}{field('phone',t('Telefone','Phone'),{required:true,type:'tel',placeholder:'+351',autoComplete:'tel',pattern:'[+0-9() \\-]{7,24}',maxLength:24})}
 {field('email','Email',{type:'email',placeholder:t('O seu email','Your email'),required:form.preferred_contact==='email',autoComplete:'email'})}{!short&&field('whatsapp',t('Número WhatsApp','WhatsApp number'),{type:'tel',placeholder:t('Se diferente do telefone','If different from phone'),maxLength:24})}
 {!short&&select('district',t('Distrito / Região','District / Region'),districts)}{field('municipality',t('Cidade / Município','City / Municipality'),{placeholder:t('A sua cidade','Your city'),autoComplete:'address-level2'})}
 {!short&&field('postal_code',t('Código postal','Postcode'),{placeholder:'0000-000',pattern:'[0-9]{4}-[0-9]{3}',maxLength:8,autoComplete:'postal-code'})}
 {select('device',t('Tipo de dispositivo','Device type'),[['iPhone','iPhone'],['Smartphone','Smartphone'],['MacBook','MacBook'],['Portátil',t('Portátil','Laptop')],['Tablet','Tablet'],['Computador',t('Computador','Computer')],['Outros dispositivos',t('Outro dispositivo','Other device')]],true)}
 {!short&&field('brand',t('Marca','Brand'),{placeholder:t('Marca do equipamento','Device brand')})}{field('model',t('Modelo','Model'),{placeholder:t('Ex.: iPhone 15, MacBook Air','E.g. iPhone 15, MacBook Air')})}
 {select('issue',t('Problema','Issue'),[['Outro',t('Outro / Não sei','Other / Not sure')],['Ecrã',t('Ecrã partido / sem imagem','Cracked screen / no display')],['Bateria',t('Bateria / autonomia','Battery / battery life')],['Carregamento',t('Não carrega','Not charging')],['Câmara',t('Câmara','Camera')],['Líquidos',t('Danos por líquidos','Liquid damage')],['Software',t('Software / lentidão','Software / slow performance')],['Teclado',t('Teclado','Keyboard')],['Não liga',t('Não liga','Will not turn on')]],true)}
 <label className="form-field wide"><span>{t('Conte-nos o que aconteceu','Tell us what happened')}</span><Textarea data-testid="quote-description" name="description" value={form.description} onChange={change} maxLength={4000} rows={3} placeholder={t('Descreva os sintomas. Não inclua palavras-passe ou dados sensíveis.','Describe the symptoms. Do not include passwords or sensitive information.')}/></label>
 </div><div className="honeypot" aria-hidden="true"><label>Website<Input data-testid="quote-website" name="website" tabIndex={-1} value={form.website} onChange={change} autoComplete="off"/></label></div><fieldset className="contact-preference"><legend>{t('Como prefere ser contactado?','How would you like to be contacted?')}</legend>{[['whatsapp','WhatsApp'],['phone',t('Telefone','Phone')],['email','Email']].map(([value,label])=><label key={value} className={form.preferred_contact===value?'selected':''}><input data-testid={`quote-contact-${value}`} name="preferred_contact" type="radio" value={value} checked={form.preferred_contact===value} onChange={change}/>{label}</label>)}</fieldset><label className="consent-label"><input data-testid="quote-consent" type="checkbox" name="consent" checked={form.consent} onChange={change} required/><span>{t('Li a','I have read the')} <Link data-testid="quote-privacy-link" to={localPath('/privacidade',lang)}>{t('Política de Privacidade','Privacy Policy')}</Link> {t('e aceito o tratamento dos meus dados para responder a este pedido.','and agree to my data being processed to respond to this enquiry.')} *</span></label>{error&&<p className="form-error" role="alert" data-testid="quote-error">{error}</p>}<button data-testid="quote-submit" className="btn btn-primary form-submit" type="submit" disabled={busy}>{busy?<Loader2 size={19} className="spin"/>:t('Pedir orçamento','Request a quote')}{!busy&&<ArrowUpRight size={18}/>}</button><p className="form-security"><ShieldCheck size={14}/>{t('Sem compromisso de reparação. Os seus dados não são vendidos.','No repair commitment. Your data is never sold.')}</p></form>
};