import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Smartphone, Laptop, Tablet, Monitor, Gamepad2, ArrowUpRight, Search, MapPin, ArrowRight, Check, ClipboardCheck, MessageCircle, Wrench, PackageCheck, ShieldCheck, Leaf, CircleCheck, BatteryCharging, ScanLine, PlugZap, Camera, Droplets, Cpu, HardDrive, Keyboard, ChevronRight, Loader2 } from 'lucide-react';
import { useSite,useText,localPath,pageText } from '../lib/context';
import { api,track,errorText } from '../lib/api';
import { SectionHeading } from './Layout';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from './ui/accordion';
import { MEDIA } from '../lib/media';

export const DEVICE_ICONS={iPhone:Smartphone,Smartphone:Smartphone,MacBook:Laptop,'Portátil':Laptop,Tablet:Tablet,Computador:Monitor,'Outros dispositivos':Gamepad2};
export const DeviceGrid=()=>{const {pages,lang}=useSite();const t=useText();return <div className="device-grid">{pages.filter(p=>p.kind==='service').map(p=>{const Icon=DEVICE_ICONS[p.device]||Smartphone;return <Link className="device-card" data-testid={`device-${p.slug}`} to={localPath('/'+p.slug,lang)} key={p.id} onClick={()=>track('device_selected',{device:p.device})}><div className="device-icon"><Icon strokeWidth={1.15} size={47}/>{p.device==='iPhone'&&<span className="device-mini-dot"/>}</div><span>{p.device==='Portátil'?t('Portátil','Laptop'):p.device==='Computador'?t('Computador','Computer'):p.device==='Outros dispositivos'?t('Outros','Other devices'):p.device}</span><ArrowUpRight size={17}/></Link>})}</div>};

export const RepairGrid=({device='iPhone'})=>{const {lang}=useSite();const t=useText();const repairs=[['ecra',ScanLine,'Ecrã partido','Cracked screen','Volte a ver tudo com clareza.','See everything clearly again.'],['bateria',BatteryCharging,'Bateria sem autonomia','Poor battery life','Mais energia para o seu dia.','More power for your day.'],['conector-carga',PlugZap,'Problemas de carga','Charging problems','Ligue-se, sem interrupções.','Stay connected, uninterrupted.'],['camera',Camera,'Câmara danificada','Camera issues','Não perca os bons momentos.','Keep the moments that matter.'],['danos-agua',Droplets,'Danos por líquidos','Liquid damage','Saiba qual o próximo passo.','Find out what to do next.'],['software',Cpu,'Software e desempenho','Software & performance','Menos esperas. Mais possibilidades.','Less waiting. More possibilities.']];return <div className="repair-grid">{repairs.map(([slug,Icon,pt,en,desc,descEn])=><Link data-testid={`repair-${slug}`} className="repair-item" to={localPath(slug==='software'?'/orcamento':'/reparacao-iphone/'+slug,lang)} state={{context:{device,issue:pt}}} key={slug}><span className="repair-icon"><Icon size={23} strokeWidth={1.6}/></span><div><h3>{t(pt,en)}</h3><p>{t(desc,descEn)}</p></div><ArrowUpRight size={18}/></Link>)}</div>};

export const HowSteps=()=>{const t=useText();const steps=[[Smartphone,'O seu dispositivo','Your device','Escolha o equipamento.','Choose your device.'],[MessageCircle,'O que aconteceu?','What happened?','Conte-nos o problema.','Tell us the problem.'],[ClipboardCheck,'Avaliação e orçamento','Assessment & quote','Conheça as suas opções.','Explore your options.'],[Wrench,'Hora de reparar','Time to repair','Avançamos com a sua aprovação.','Only with your approval.'],[PackageCheck,'De volta a si','Back in your hands','Pronto para o próximo capítulo.','Ready for its next chapter.']];return <div className="how-steps">{steps.map(([Icon,title,en,desc,den],i)=><div className="how-step" key={title} data-testid={`how-step-${i+1}`}><div className="step-top"><span className="step-number">0{i+1}</span><Icon size={23} strokeWidth={1.5}/></div><h3>{t(title,en)}</h3><p>{t(desc,den)}</p></div>)}</div>};

export const LocationSearch=({standalone=false})=>{const {lang}=useSite();const t=useText();const [q,setQ]=useState('');const [results,setResults]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const search=async e=>{e?.preventDefault();if(q.trim().length<2)return;setBusy(true);setError('');try{setResults((await api.get('/locations/search',{params:{q}})).data.results)}catch(err){setError(errorText(err))}finally{setBusy(false)}};return <div className={`location-search ${standalone?'standalone':''}`}><form onSubmit={search}><MapPin size={21}/><input data-testid="location-search-input" aria-label={t('Cidade ou código postal','City or postcode')} value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Introduza a sua cidade ou código postal','Enter your city or postcode')} minLength={2} required/><button className="btn btn-primary" data-testid="location-search-button" type="submit" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<Search size={18}/>}<span>{t('Pesquisar','Search')}</span></button></form>{results!==null&&<div className="location-results" data-testid="location-search-results">{results.length?results.map(r=><Link data-testid={`location-result-${r.slug}`} key={r.slug} to={localPath(r.page?'/'+r.page.slug:'/orcamento',lang)} state={{context:{municipality:r.city,district:r.district}}} onClick={()=>track('location_selected',{municipality:r.city})}><MapPin size={18}/><div><strong>{r.city}</strong><span>{r.district} · {r.page?t('Consultar atendimento','View service details'):t('Confirmar disponibilidade','Check availability')}</span></div><ArrowUpRight size={17}/></Link>):<div className="location-empty"><p data-testid="location-no-results">{t('Não encontrámos essa localização. Indique a sua cidade no pedido para confirmarmos a disponibilidade.','We could not find that location. Include your city in an enquiry so we can check availability.')}</p><Link className="text-link" data-testid="location-enquire" to={localPath('/orcamento',lang)} state={{context:{municipality:q}}}>{t('Consultar disponibilidade','Check availability')}<ArrowUpRight size={17}/></Link></div>}</div>}{error&&<p className="form-error" data-testid="location-search-error">{error}</p>}<p className="location-note"><ShieldCheck size={14}/>{t('A disponibilidade e a forma de atendimento são confirmadas para a sua zona.','Availability and service arrangements are confirmed for your area.')}</p></div>};

export const FAQs=({items,id='faq'})=>{const {lang,faqs}=useSite();const t=useText();const list=items?.length?items:faqs||[];return <div className="faq-section"><div><div className="eyebrow">{t('SEM COMPLICAÇÕES','KEEPING IT SIMPLE')}</div><h2 data-testid={`${id}-heading`}>{t('Ainda tem dúvidas?','Still have questions?')}</h2><p>{t('Respostas claras, antes de avançar.','Clear answers, before you proceed.')}</p></div><Accordion type="single" collapsible className="faq-accordion">{list.map((f,i)=><AccordionItem key={i} value={`faq-${i}`}><AccordionTrigger data-testid={`${id}-question-${i}`}>{lang==='en'?(f.q_en||f.q):f.q}</AccordionTrigger><AccordionContent data-testid={`${id}-answer-${i}`}>{lang==='en'?(f.a_en||f.a):f.a}</AccordionContent></AccordionItem>)}</Accordion></div>};

export const BlogGrid=({limit})=>{const {pages,lang}=useSite();const t=useText();const articles=pages.filter(p=>p.kind==='blog').slice(0,limit||100);const covers=['/images/repair-small.webp',MEDIA.phone,MEDIA.macbook];return <div className="blog-grid">{articles.map((p,i)=><Link data-testid={`blog-card-${p.id}`} className="blog-card" key={p.id} to={localPath('/'+p.slug,lang)}><div className="blog-image"><img src={p.image&&p.image!=='/images/repair-small.webp'?p.image:covers[i%3]} width="680" height="420" alt={pageText(p,'title',lang)} loading="lazy"/><span>{lang==='en'&&p.category==='Conselhos'?'Tips':p.category}</span></div><div className="blog-card-body"><span className="article-meta">{t('GUIA GLENNTEK','GLENNTEK GUIDE')}<span>4 min</span></span><h3>{pageText(p,'title',lang)}</h3><span className="text-link">{t('Ler artigo','Read article')}<ArrowUpRight size={16}/></span></div></Link>)}</div>};