import { useState,useEffect } from 'react';
import { Routes,Route,NavLink,Link,useNavigate } from 'react-router-dom';
import { LayoutDashboard,Inbox,Files,Settings,LogOut,ArrowUpRight,ShieldCheck,Loader2,Menu,X,LockKeyhole } from 'lucide-react';
import { api,errorText,setCsrf } from '../lib/api';
import { Logo } from '../components/Layout';
import { Input } from '../components/ui/input';
import Dashboard from './Dashboard';
import Leads from './Leads';
import ContentManager from './ContentManager';
import SettingsPage from './SettingsPage';
import './admin.css';

export default function AdminApp(){
 const [user,setUser]=useState(null);const [loading,setLoading]=useState(true);const [setup,setSetup]=useState(false);const [open,setOpen]=useState(false);const navigate=useNavigate();
 useEffect(()=>{api.get('/auth/me').then(r=>{setUser(r.data);setCsrf(r.data.csrf)}).catch(()=>api.get('/auth/status').then(r=>setSetup(r.data.setup_required))).finally(()=>setLoading(false))},[]);
 const login=(data)=>{setUser(data);setCsrf(data.csrf);navigate('/admin')};
 const logout=async()=>{try{await api.post('/auth/logout')}finally{setUser(null);setCsrf('');setSetup(false);navigate('/admin')}};
 if(loading)return <div className="page-loading"><Loader2 className="spin"/></div>;
 if(!user)return <AdminLogin setup={setup} onLogin={login}/>;
 return <div className="admin-app"><aside className={`admin-sidebar ${open?'open':''}`}><Link to="/admin" data-testid="admin-logo"><Logo/></Link><div className="admin-workspace">GESTÃO GLENNTEK</div><nav>{[['/admin',LayoutDashboard,'Visão geral'],['/admin/leads',Inbox,'Pedidos de orçamento'],['/admin/content',Files,'Conteúdos e SEO'],['/admin/settings',Settings,'Configurações']].map(([path,Icon,label])=><NavLink key={path} data-testid={`admin-nav-${path.split('/').pop()||'dashboard'}`} to={path} end={path==='/admin'} onClick={()=>setOpen(false)}><Icon size={18}/>{label}</NavLink>)}</nav><div className="admin-sidebar-bottom"><Link data-testid="admin-view-site" to="/" target="_blank">Ver website<ArrowUpRight size={15}/></Link><div className="admin-user"><span>{user.email.slice(0,1).toUpperCase()}</span><div><strong>Administrador</strong><small data-testid="admin-user-email">{user.email}</small></div></div><button data-testid="admin-logout" onClick={logout}><LogOut size={16}/>Terminar sessão</button></div></aside><div className="admin-main"><header className="admin-topbar"><button className="admin-mobile-toggle" data-testid="admin-menu-toggle" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><span><span className="admin-online-dot"/>Área de administração</span><span><ShieldCheck size={14}/>Ligação segura</span></header><div className="admin-content"><Routes><Route index element={<Dashboard/>}/><Route path="leads" element={<Leads/>}/><Route path="content" element={<ContentManager/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="*" element={<Dashboard/>}/></Routes></div></div></div>
}

function AdminLogin({setup,onLogin}){const [form,setForm]=useState({email:'',password:'',setup_token:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await api.post(setup?'/auth/setup':'/auth/login',form);onLogin(data)}catch(err){setError(errorText(err))}finally{setBusy(false)}};return <div className="admin-login-page"><div className="admin-login-brand"><Logo/><div><span className="eyebrow">ÁREA RESERVADA</span><h1>O próximo capítulo<br/>da GlennTek<br/><span>começa aqui.</span></h1><p>Os seus pedidos, os seus conteúdos,<br/>o seu negócio. Num só lugar.</p></div><span className="login-brand-footer">GlennTek · Portugal</span></div><div className="admin-login-form"><div className="login-form-inner"><span className="login-lock"><LockKeyhole size={24}/></span><h2 data-testid="admin-login-title">{setup?'Criar acesso de administrador':'Bem-vindo de volta.'}</h2><p>{setup?'Utilize o código privado de configuração para criar a sua conta.':'Entre na sua área de gestão GlennTek.'}</p><form data-testid="admin-login-form" onSubmit={submit}>{setup&&<label className="form-field"><span>Código de configuração</span><Input data-testid="admin-setup-token" type="password" value={form.setup_token} onChange={e=>setForm({...form,setup_token:e.target.value})} required autoComplete="off"/></label>}<label className="form-field"><span>Email</span><Input data-testid="admin-login-email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} autoComplete="username" required/></label><label className="form-field"><span>Palavra-passe {setup?'(mínimo 12 caracteres)':''}</span><Input data-testid="admin-login-password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={12} maxLength={72} autoComplete={setup?'new-password':'current-password'} required/></label>{error&&<p className="form-error" data-testid="admin-login-error">{error}</p>}<button className="btn btn-primary" data-testid="admin-login-submit" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:setup?'Criar conta segura':'Entrar no painel'}<ArrowUpRight size={17}/></button></form><Link data-testid="admin-login-home" to="/">← Voltar ao website</Link></div></div></div>}