import { useEffect,useState } from 'react';
import { Link,useLocation } from 'react-router-dom';
import { ArrowUpRight, ChevronRight, MapPin, ShieldCheck, Loader2, Building2 } from 'lucide-react';
import { useSite,useText,localPath,pageText } from '../lib/context';
import { api,errorText } from '../lib/api';
import { Breadcrumb,SectionHeading } from '../components/Layout';
import { ContactActions } from '../components/ContactActions';
import { QuoteForm } from '../components/QuoteForm';
import { FAQs,HowSteps,RepairGrid } from '../components/Sections';

export const Prose=({text=''})=><div className="prose">{text.split('\n\n').filter(Boolean).map((p,i)=>p.length<90&&!p.includes('. ')?<h2 data-testid={`content-heading-${i}`} key={i}>{p}</h2>:<p data-testid={`content-paragraph-${i}`} key={i}>{p}</p>)}</div>;
export const NotFound=()=>{const {lang}=useSite();const t=useText();return <div className="container not-found"><span>404</span><h1 data-testid="not-found-title">{t('Esta ligação precisa de outro caminho.','This link needs a different route.')}</h1><p>{t('A página não existe ou ainda não está publicada.','This page does not exist or has not been published.')}</p><Link className="btn btn-primary" data-testid="not-found-home" to={localPath('/',lang)}>{t('Voltar ao início','Back to home')}<ArrowUpRight size={17}/></Link></div>};
export default function ContentPage(){
 const {pathname}=useLocation();const {lang,pages}=useSite();const t=useText();const [page,setPage]=useState(null);const [error,setError]=useState(null);const [loading,setLoading]=useState(true);const slug=pathname.replace(/^\/en(?=\/|$)/,'').replace(/^\/+|\/+$/g,'');
 useEffect(()=>{let active=true;setLoading(true);setError(null);api.get('/pages/'+slug).then(r=>{if(active)setPage(r.data)}).catch(e=>{if(active)setError(e.response?.status===404?'404':errorText(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[slug]);
 if(loading)return <div className="page-loading" data-testid="content-loading"><Loader2 className="spin"/></div>;
 if(error==='404')return <NotFound/>;
 if(error)return <div className="error-page"><p data-testid="content-load-error">{error}</p><button data-testid="content-retry" className="btn btn-primary" onClick={()=>window.location.reload()}>{t('Tentar novamente','Try again')}</button></div>;
 const title=pageText(page,'title',lang),intro=pageText(page,'intro',lang),content=pageText(page,'content',lang);const context=Object.fromEntries(['service','device','brand','model','district','municipality'].map(k=>[k,page[k]||'']));
 const related=pages.filter(p=>p.id!==page.id&&(p.kind==='service'||(p.kind==='repair'&&p.device===page.device))).slice(0,9);
 const models=pages.filter(p=>p.kind==='model'&&(p.device===page.device||p.brand===page.brand));
 const local=['location','service_location','service_area','municipality','district'].includes(page.kind);
 if(page.kind==='blog')return <div className="container"><Breadcrumb items={[{label:'Blog',path:'/blog'},{label:title}]}/><div className="article-layout"><div className="page-heading"><div className="eyebrow">{page.category} · GLENNTEK</div><h1 data-testid="article-title">{title}</h1><p>{intro}</p></div><img className="article-hero-image" src={page.image||'/images/repair-small.webp'} width="760" height="510" alt={title}/><Prose text={content}/><div className="article-cta"><h2>{t('Precisa de uma avaliação para o seu equipamento?','Need an assessment for your device?')}</h2><ContactActions id="article"/></div></div></div>;
 return <><section className="page-hero service-hero"><img className="service-hero-image" src={page.image||'/images/repair-hero.webp'} width="1264" height="848" alt={t('Avaliação de um equipamento eletrónico','Assessment of an electronic device')}/><div className="container"><Breadcrumb items={[{label:local?t('Localizações','Locations'):t('Reparações','Repairs'),path:local?'/localizacoes':'/reparacoes'},...(page.municipality&&page.kind==='service_location'?[{label:page.municipality}]:[]),{label:title}]}/><div className="page-heading"><div className="eyebrow">GLENNTEK · {page.device||t('UMA SEGUNDA OPORTUNIDADE','A SECOND CHANCE')}{page.municipality?' · '+page.municipality:''}</div><h1 data-testid="content-page-title">{title}</h1><p data-testid="content-page-intro">{intro}</p><ContactActions id="service-hero" context={context}/>{!page.verified&&<div className="availability-note" data-testid="service-availability-note"><ShieldCheck size={13}/>{t('Disponibilidade, peças, preços e prazos sujeitos a avaliação do equipamento.','Availability, parts, prices and timing are subject to device assessment.')}</div>}</div></div></section>
 <section className="section container"><div className="content-two-col"><div>{page.device==='iPhone'&&<div className="service-links">{pages.filter(p=>p.kind==='repair'&&p.id!==page.id).map(p=><Link data-testid={`subservice-${p.id}`} to={localPath('/'+p.slug,lang)} key={p.id}>{pageText(p,'title',lang)}<ArrowUpRight size={14}/></Link>)}</div>}<Prose text={content||intro}/>{models.length>0&&<div className="service-links">{models.map(p=><Link data-testid={`model-link-${p.id}`} key={p.id} to={localPath('/'+p.slug,lang)}>{p.title}<ArrowUpRight size={14}/></Link>)}</div>}{local&&<div className="local-details"><h2>{t('Atendimento na sua zona','Service in your area')}</h2><p>{page.coverage}</p><p>{page.service_method}</p>{page.physical&&page.address&&<div className="info-note"><Building2 size={22}/><p data-testid="physical-address">{page.address}</p><p data-testid="physical-hours">{page.hours}</p>{page.maps_url&&<a data-testid="physical-directions" href={page.maps_url} target="_blank" rel="noopener noreferrer" className="text-link">{t('Obter direções','Get directions')}<ArrowUpRight size={15}/></a>}</div>}{page.nearby?.length>0&&<p className="info-note">{t('Áreas próximas:','Nearby areas:')} {page.nearby.join(' · ')}</p>}</div>}</div><aside className="content-sidebar"><h3>{t('Outras reparações','Other repairs')}</h3>{related.map(p=><Link data-testid={`related-service-${p.id}`} to={localPath('/'+p.slug,lang)} key={p.id}>{pageText(p,'title',lang)}<ChevronRight size={14}/></Link>)}<div className="info-note">{t('Não sabe qual é a avaria? Descreva os sintomas no formulário. Não precisa de fazer o diagnóstico.','Not sure what is wrong? Describe the symptoms in the form. You do not need to diagnose it yourself.')}</div>{local&&pages.filter(p=>p.verified&&p.status==='published'&&p.municipality&&p.id!==page.id).slice(0,5).map(p=><Link data-testid={`related-location-${p.id}`} key={p.id} to={localPath('/'+p.slug,lang)}>{p.title}<MapPin size={14}/></Link>)}</aside></div></section>
 {page.kind!=='campaign'&&<section className="section soft-section"><div className="container"><SectionHeading id="content-process" eyebrow={t('CLAREZA EM CADA PASSO','CLARITY AT EVERY STEP')} title={t('Como funciona a reparação','How repair works')}/><HowSteps/></div></section>}
 <section className="section quote-section"><div className="container quote-layout"><div className="quote-intro"><span className="eyebrow">{t('VAMOS CONVERSAR','LET’S TALK')}</span><h2>{t('Peça uma avaliação. Decida com confiança.','Request an assessment. Decide with confidence.')}</h2><p>{t('Partilhe os detalhes do equipamento. Confirmamos as opções antes de avançar.','Share your device details. We confirm the options before proceeding.')}</p><ContactActions id="content-quote" context={context} quote={false}/></div><QuoteForm key={page.id} context={context} short={page.kind==='campaign'}/></div></section><section className="section container"><FAQs items={page.faqs} id="content-faq"/></section>
 </>
}