import { Link } from 'react-router-dom';
import { ArrowUpRight, Check, ShieldCheck, MessageCircle, Leaf, CircleCheck, ArrowDown, Sparkles, MapPin, Wrench } from 'lucide-react';
import { useSite,useText,localPath } from '../lib/context';
import { SectionHeading } from '../components/Layout';
import { ContactActions } from '../components/ContactActions';
import { DeviceGrid,RepairGrid,HowSteps,LocationSearch,FAQs,BlogGrid } from '../components/Sections';
import { QuoteForm } from '../components/QuoteForm';
import { MEDIA } from '../lib/media';

export default function Home(){const {lang,pages}=useSite();const t=useText();const reviews=pages.filter(p=>p.kind==='review'&&p.verified);return <>
 <section className="home-hero"><img className="hero-photo" src="/images/repair-hero.webp" width="1264" height="848" alt={t('Reparação de um smartphone numa bancada técnica','Smartphone repair on a technician’s workbench')} fetchPriority="high"/><div className="hero-wash"/><div className="container hero-inner"><div className="hero-copy"><div className="hero-eyebrow" data-testid="hero-eyebrow"><span/>{t('REPARAR É DAR UMA NOVA VIDA.','REPAIR IS A SECOND CHANCE.')}</div><h1 data-testid="hero-title">{t('Reparação de','Repair for')}<br/>{t('Telemóveis, Tablets','Phones, Tablets')}<br/>{t('e Computadores','and Computers')}<br/><span>{t('em Portugal.','in Portugal.')}</span></h1><p className="hero-description" data-testid="hero-description">{t('O seu dia a dia não pode ficar em pausa. Conte-nos o que aconteceu ao seu equipamento — vamos encontrar o próximo passo.','Your everyday life cannot stay on hold. Tell us what happened to your device — let’s find the next step.')}</p><ContactActions id="hero"/><div className="hero-assurances" data-testid="hero-assurances"><span><Check size={14}/>{t('Orçamento antes de reparar','Quote before repair')}</span><span><Check size={14}/>{t('Sem compromisso','No commitment')}</span></div></div><div className="hero-caption" data-testid="hero-caption"><span className="caption-icon"><Wrench size={19}/></span><div><strong>{t('Cada detalhe conta.','Every detail matters.')}</strong><span>{t('A sua tecnologia merece cuidado.','Your technology deserves care.')}</span></div><span className="caption-dot"/></div></div></section>
 <div className="trust-strip"><div className="container trust-inner">{[[ShieldCheck,'Avaliação antes da reparação','Assessment before repair'],[MessageCircle,'Comunicação simples e direta','Simple, direct communication'],[CircleCheck,'Decisão sempre nas suas mãos','The decision is always yours'],[Leaf,'Reparar é uma escolha consciente','Repair is a mindful choice']].map(([Icon,pt,en])=><span key={pt} data-testid={`trust-${pt.split(' ')[0].toLowerCase()}`}><Icon size={19} strokeWidth={1.5}/>{t(pt,en)}</span>)}</div></div>
 <section className="section devices-section container"><SectionHeading id="devices" eyebrow={t('VAMOS COMEÇAR','LET’S GET STARTED')} title={t('O que precisa de reparar?','What needs repairing?')} description={t('Escolha o seu equipamento. Nós ajudamos no próximo passo.','Choose your device. We’ll help with the next step.')} link={localPath('/reparacoes',lang)} label={t('Todas as reparações','All repairs')}/><DeviceGrid/></section>
 <section className="section soft-section"><div className="container"><SectionHeading id="repairs" eyebrow={t('PEQUENOS PROBLEMAS. NOVAS POSSIBILIDADES.','SMALL PROBLEMS. NEW POSSIBILITIES.')} title={t('O problema pode ter solução.','There may be a fix for that.')} description={t('Dos acidentes do dia a dia aos sinais de desgaste.','From everyday accidents to the signs of wear.')} link={localPath('/reparacoes',lang)} label={t('Explorar serviços','Explore services')}/><RepairGrid/></div></section>
 <section className="section container"><SectionHeading id="how" eyebrow={t('SIMPLES, DO INÍCIO AO FIM','SIMPLE, FROM START TO FINISH')} title={t('De volta ao que importa. Em 5 passos.','Back to what matters. In 5 steps.')}/><HowSteps/></section>
 <section className="location-band"><div className="container location-band-inner"><div><span className="eyebrow">{t('PERTO DO SEU DIA A DIA','CLOSER TO YOUR EVERYDAY')}</span><h2 data-testid="home-location-title">{t('Onde precisa de ajuda?','Where do you need help?')}</h2><p>{t('Diga-nos onde está. Vamos confirmar as opções para si.','Tell us where you are. We’ll check your options.')}</p></div><LocationSearch/></div></section>
 <section className="section container why-section"><div className="why-image"><img loading="lazy" src={MEDIA.workshop} width="850" height="700" alt={t('Intervenção técnica num smartphone','Technical work on a smartphone')}/><div className="why-image-label"><Leaf size={22}/><span>{t('Reparar hoje.','Repair today.')}<strong>{t('Repensar o amanhã.','Rethink tomorrow.')}</strong></span></div></div><div className="why-copy"><span className="eyebrow">{t('A DIFERENÇA ESTÁ NO CUIDADO','THE DIFFERENCE IS IN THE CARE')}</span><h2 data-testid="why-title">{t('A sua tecnologia.','Your technology.')}<br/>{t('A nossa atenção.','Our attention.')}</h2><p>{t('Por trás de cada equipamento estão as suas fotografias, o seu trabalho e as suas pessoas. É por isso que o próximo passo merece ser bem pensado.','Behind every device are your photos, your work and your people. That is why the next step deserves careful thought.')}</p><div className="why-points">{[[ShieldCheck,'Clareza antes de avançar','Clarity before moving forward','Conheça o orçamento e as condições antes de decidir.','Know the quote and conditions before deciding.'],[MessageCircle,'Uma conversa, não uma complicação','A conversation, not a complication','Fale connosco pelo método que lhe dá mais jeito.','Contact us in whichever way suits you best.'],[Leaf,'Mais reparar. Menos substituir.','More repair. Less replacement.','Uma decisão informada para si e para o planeta.','An informed choice for you and the planet.']].map(([Icon,pt,en,desc,den])=><div key={pt}><Icon size={21}/><div><h3>{t(pt,en)}</h3><p>{t(desc,den)}</p></div></div>)}</div><Link data-testid="home-about-link" className="text-link" to={localPath('/sobre-nos',lang)}>{t('Conheça a Glenntek','Meet Glenntek')}<ArrowUpRight size={17}/></Link></div></section>
 {reviews.length>0&&<section className="section soft-section"><div className="container"><SectionHeading id="reviews" title={t('Quem nos procura, conta.','Customer experiences.')}/><div className="review-grid">{reviews.map(r=><blockquote data-testid={`review-${r.id}`} key={r.id}><span>{'★'.repeat(r.rating)}</span><p>{lang==='en'?(r.content_en||r.content):r.content}</p><cite>{r.review_author}</cite><a href={r.source_url} data-testid={`review-source-${r.id}`} target="_blank" rel="noopener noreferrer">{t('Ver avaliação original','View original review')}</a></blockquote>)}</div></div></section>}
 <section className="section quote-section"><div className="container quote-layout"><div className="quote-intro"><span className="eyebrow">{t('O PRIMEIRO PASSO É SEU','THE FIRST STEP IS YOURS')}</span><h2 data-testid="home-quote-title">{t('Vamos dar uma nova vida ao seu equipamento?','Let’s give your device a second life?')}</h2><p>{t('Peça o seu orçamento. Diga-nos o que precisa e como prefere ser contactado.','Request a quote. Tell us what you need and how you would like us to contact you.')}</p><div className="quote-intro-checks"><span><Check/>{t('Sem compromisso de reparação','No repair commitment')}</span><span><Check/>{t('Uma resposta ajustada ao seu equipamento','A response tailored to your device')}</span><span><Check/>{t('Os seus dados tratados com cuidado','Your data handled with care')}</span></div><div className="quote-help"><MessageCircle size={22}/><p>{t('Prefere conversar?','Prefer a conversation?')}<strong>{t('Estamos à distância de uma mensagem.','We’re a message away.')}</strong></p></div><ContactActions id="home-quote" quote={false}/></div><QuoteForm/></div></section>
 <section className="section container"><SectionHeading id="blog" eyebrow={t('CUIDAR TAMBÉM É SABER','KNOWLEDGE IS PART OF CARE')} title={t('Mais conhecimento. Melhor tecnologia.','More knowledge. Better technology.')} link={localPath('/blog',lang)} label={t('Visitar o blog','Visit the blog')}/><BlogGrid limit={3}/></section>
 <section className="section container faq-band"><FAQs/></section>
 </>}